---
users_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63663034323461623232656262636130363930353965633638393736346561356434396665393437
          3739613034306562313163353462333334613530333331390a326262666566323765326134393736
          39616331316134383039633766643963363835666334626238373530386335613332393564643537
          6634326563343134350a663035313335636235643964373132346131373064633863313362386461
          6331