---
- name: Adding Ansible user
  ansible.builtin.user:
    name: ans
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "!"

- name: Adding SSH-key for ans user
  ansible.posix.authorized_key:
    user: ans
    state: present
    key: "{{ lookup('file', '/home/rm/.ssh/id_ed25519.pub') }}"

- name: Adding rm user
  ansible.builtin.user:
    name: rm
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "!" 

- name: Adding SSH-key for rm user
  ansible.posix.authorized_key:
    user: rm
    state: present
    key: "{{ lookup('file', '/home/rm/.ssh/id_ed25519.pub') }}"
