$ANSIBLE_VAULT;1.1;AES256
34336636336439363236663138326531383030666564383532353834383232393234363632396234
6665313761356432353964653634313133663531336233650a663430333830663464633636643134
38326561326136376239626633363831626565393934613137663938306164626363326464333935
3430376330623332620a626133613333373237623236313139393331383333636363656563663938
35323530643761646334396237303630646432633733613238613664613762663039
